Enhance CI workflow to include tagging and pushing of the latest Docker image, and add deployment status check for AWS App Runner

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,10 +55,13 @@ jobs:
         run : | 
             docker build -t $REGISTRY/rocketseat-ci:$TAG .
             docker push $REGISTRY/rocketseat-ci:$TAG
+            docker tag $REGISTRY/rocketseat-ci:$TAG $REGISTRY/rocketseat-ci:latest
+            docker push $REGISTRY/rocketseat-ci:latest
             IMAGE=$(echo $REGISTRY/rocketseat-ci:$TAG)
             echo "image=$IMAGE" >> $GITHUB_OUTPUT
 
       - name: Deploy to AWS App Runner
+        id: deploy-app-runner
         uses: awslabs/amazon-app-runner-deploy@main
         with:
           service: rocksetseat-api
@@ -68,3 +71,13 @@ jobs:
           memory: 2
           port: 3000
           image: ${{ steps.build-image.outputs.image }}
+          wait-for-service-stability-seconds: 180
+
+      - name: App Runner check  - Notify deployment
+        run: |
+          if [ "${{ steps.deploy-app-runner.outputs.status }}" != "SUCCEEDED" ]; then
+            echo "Deployment failed"
+            exit 1
+          else
+            echo "Deployment succeeded... ${{ steps.deploy-app-runner.outputs.service_url }}"
+          fi
